#!/usr/bin/env bash

# [start-readme]
#
# List all the TODOs in our JavaScript files and stylesheets.
#
# [end-readme]

echo "JavaScript TODOs"
rg --line-number --glob '*.js' --glob '*.ts' 'TODO' . --glob '!node_modules/**'

echo

echo "Stylesheet TODOs"
rg --line-number --glob '*.*css' 'TODO' . --glob '!node_modules/**'
